### ISSUE TITLE
Rederer breaks when focal point set to 0

### ISSUE THREAD

**Issue by Luiginotcool** [jameshball/osci-render#102]
When I set the focal point to 0, the renderer breaks, even after reseting the focal point to a sensible value.

**Comment by jameshball** [comment]
Thanks for raising this issue! Could I confirm what version of osci-render you are using and whether you have changed the range of the focal point slider?

Does the program become completely unresponsive or does the audio freeze/stop?

If you are on a version with the project select screen when you launch the program, would you be able to reproduce the error and then upload the relevant log file generated? You can access this using the "Open log folder" button in the project select screen.

Thank you!

**Comment by Luiginotcool** [comment]
Hi! 
I am using osci-render v1.27.2 and I haven't changed the range of the focal point slider.
The program is still completely responsive, however the audio stops other than a pulse of sound every second or so.
The file log is very large, almost a gigabyte
![LogSize](https://user-images.githubusercontent.com/59624298/179428338-3ef2c241-bd2b-4e95-93f8-2d91a7134dbc.PNG)

However it's just repeating the same error over and over:

Jul 17, 2022 11:51:43 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @56d80d3b'
Jul 17, 2022 11:57:22 PM sh.ball.audio.engine.ConglomerateAudioEngine$BufferedChannelGenerator run
SEVERE: Index 504 out of bounds for length 504
java.lang.IndexOutOfBoundsException: Index 504 out of bounds for length 504
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at sh.ball.audio.ShapeAudioPlayer.getCurrentShape(ShapeAudioPlayer.java:327)
	at sh.ball.audio.ShapeAudioPlayer.generateChannels(ShapeAudioPlayer.java:154)
	at sh.ball.audio.engine.ConglomerateAudioEngine$BufferedChannelGenerator.run(ConglomerateAudioEngine.java:136)
	at java.base/java.lang.Thread.run(Unknown Source)

Jul 17, 2022 11:57:22 PM sh.ball.audio.engine.ConglomerateAudioEngine$BufferedChannelGenerator run
SEVERE: Index 504 out of bounds for length 504
java.lang.IndexOutOfBoundsException: Index 504 out of bounds for length 504
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at sh.ball.audio.ShapeAudioPlayer.getCurrentShape(ShapeAudioPlayer.java:327)
	at sh.ball.audio.ShapeAudioPlayer.generateChannels(ShapeAudioPlayer.java:154)
	at sh.ball.audio.engine.ConglomerateAudioEngine$BufferedChannelGenerator.run(ConglomerateAudioEngine.java:136)
	at java.base/java.lang.Thread.run(Unknown Source)

and so on ...

**Comment by jameshball** [comment]
Thank you! This is very helpful and hopefully I'll have a fix for this later today.

Another note, there should definitely be a max size on log files... Good flag!

**Comment by Luiginotcool** [comment]
You're welcome!
I just wanted to add that this software is really excellent especially the ability to create sounds using Lua files ! I'm really enjoying playing around with it

**Comment by jameshball** [comment]
Thanks for the kind words! I'd love to see what you get up to :)

Just something to add about this issue - do you have a specific project or .obj file where this occurs or do you always face this issue? (e.g. when creating a new project with the default cube)

**Comment by jameshball** [comment]
Should be all fixed :) https://github.com/jameshball/osci-render/releases
