### ISSUE TITLE
Cannot run jar file

### ISSUE THREAD

**Issue by accurateisaiah** [jameshball/osci-render#29]
**Describe the bug**
When running jar file with the command given I get a long error message

**To Reproduce**
Steps to reproduce the behaviour:
1. Type the command to start the jar file
2. error pops up

**Expected behaviour**
The program to start

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [21h1.]

**Additional context**
Error in CMD:

```
C:\Users\zoome>java "-Dfile.encoding=UTF8" -jar "C:\Users\zoome\Desktop\osci-render-win-1.7.2.jar"
Jun. 23, 2021 2:03:51 P.M. com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5bef1c6a'
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: javafx.fxml.LoadException:
file:/C:/Users/zoome/Desktop/osci-render-win-1.7.2.jar!/fxml/osci-render.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2707)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2685)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2517)
        at sh.ball.gui.Gui.start(Gui.java:29)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:474)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        ... 1 more
Caused by: xt.audio.XtException
        at xt.audio.Utility.handleError(Utility.java:61)
        at xt.audio.XtDevice.supportsFormat(XtDevice.java:55)
        at sh.ball.audio.engine.XtAudioEngine.devices(XtAudioEngine.java:165)
        at sh.ball.audio.ShapeAudioPlayer.devices(ShapeAudioPlayer.java:242)
        at sh.ball.gui.Controller.initialize(Controller.java:256)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2655)
        ... 12 more
```

**Comment by jameshball** [comment]
Thanks for reporting this, have you tried running the program using the .exe rather than .jar and do you experience the same issue?

If you have the same issue with an .exe, could you please try [v1.6.8](https://github.com/jameshball/osci-render/releases/tag/v1.6.8) and see if you have the same issue?

Thanks!

**Comment by jameshball** [comment]
Could you also let me know if the [latest version 1.7.3](https://github.com/jameshball/osci-render/releases/tag/v1.7.3) works? This will hopefully address your problem

**Comment by accurateisaiah** [comment]
Thanks! 1.6.8 (exe) worked! I will test the jar version of 1.7.3 after.

**Comment by jameshball** [comment]
Closing assuming it works on 1.7.3, please re-open if not :)
