### ISSUE TITLE
MacOS Jar version 1.8.0 throws exception upon being run

### ISSUE THREAD

**Issue by wdhg** [jameshball/osci-render#31]
After running the command `java -jar osci-render-mac-1.8.0.jar` it outputs the following error message:

```
Jul 04, 2021 8:06:12 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @76e041cf'
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'xt-audio':
dlopen(libxt-audio.dylib, 9): image not found
dlopen(libxt-audio.dylib, 9): image not found
dlopen(/Users/wdhg/Library/Frameworks/xt-audio.framework/xt-audio, 9): image not found
dlopen(/Library/Frameworks/xt-audio.framework/xt-audio, 9): image not found
dlopen(/System/Library/Frameworks/xt-audio.framework/xt-audio, 9): image not found
Native library (darwin/libxt-audio.dylib) not found in resource path (osci-render-mac-1.8.0.jar)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at xt.audio.Utility.<clinit>(Utility.java:47)
        at xt.audio.XtAudio.<clinit>(XtAudio.java:16)
        at sh.ball.audio.engine.XtAudioEngine.devices(XtAudioEngine.java:134)
        at sh.ball.audio.engine.ConglomerateAudioEngine.devices(ConglomerateAudioEngine.java:45)
        at sh.ball.audio.ShapeAudioPlayer.devices(ShapeAudioPlayer.java:233)
        at sh.ball.gui.Controller.initialize(Controller.java:256)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2655)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2517)
        at sh.ball.gui.Gui.start(Gui.java:30)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:474)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libxt-audio.dylib, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
                ... 17 more
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libxt-audio.dylib, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
                ... 17 more
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/wdhg/Library/Frameworks/xt-audio.framework/xt-audio, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
                ... 17 more
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/xt-audio.framework/xt-audio, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
                ... 17 more
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/xt-audio.framework/xt-audio, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
                ... 17 more
        Suppressed: java.io.IOException: Native library (darwin/libxt-audio.dylib) not found in resource path (osci-render-mac-1.8.0.jar)
                at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
                ... 17 more
```

Here is my Java version:

```
$ java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

**Comment by jameshball** [comment]
Thanks, could you please try again with [v1.8.1](https://github.com/jameshball/osci-render/releases/tag/v1.8.1) and let me know if that fixes it

**Comment by jameshball** [comment]
Now working
